### ISSUE TITLE
Professor does not have access to professor

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#411]
* log in as rexifer
* click semester SP-2016
* click Section
* click AE-468-1
* click on prof link
* (incorr) receive "access denied"

(note that Student [ex Lhawkins *does* have access in some things, but in Section, also denied)

**Comment by bjmckenz** [comment]
fixed as part of #95.

**Comment by liannadevries09** [comment]
The section in your test data was not available but I just used a different professor instead. This has failed. I can view a different professor's profile data
![image](https://user-images.githubusercontent.com/71474266/116010348-6c228a80-a5ec-11eb-8fd7-366acf2b3457.png)

**Comment by bjmckenz** [comment]
please retest now that PR is merged. I did, works for me.

**Comment by liannadevries09** [comment]
I still have access to a professors info as a different professor. 
![image](https://user-images.githubusercontent.com/71474266/117748326-c4a57a80-b1dd-11eb-92a1-155c528699ab.png)

**Comment by bjmckenz** [comment]
Not a failure. You can see it but not edit it.
